# Generated by Django 3.2.9 on 2021-12-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_auto_20211228_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='product_quantity',
            new_name='quantity_product',
        ),
    ]
