# Generated by Django 3.2.9 on 2022-01-28 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_auto_20211229_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_detail',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
