# Generated by Django 3.2.9 on 2022-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_auto_20220128_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=0),
        ),
    ]
