# Generated by Django 3.2.9 on 2022-01-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='work_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.work_section'),
        ),
    ]
