# Generated by Django 3.2.9 on 2022-01-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220111_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='work_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.work_section'),
        ),
    ]
